return {
	"folke/which-key.nvim",
	event = "VimEnter",
	opts = {
		delay = 0,
		icons = {
			mappings = vim.g.have_nerd_font,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},

		-- Document existing key chains
		spec = {
			{ "<leader>f", group = "[f]ind" },
			{ "<leader>g", group = "[g]it", mode = { "n", "v" } },
			{ "<leader>gh", group = "[g]it [h]unk", mode = { "n", "v" } },
			{ "<leader>l", group = "[l]atex" },
			{ "<leader>o", group = "[o]bsidian" },
			{ "<leader>p", group = "[p]review" },
			{ "<leader>r", group = "[r]emote" },
			{ "<leader>t", group = "[t]oggle" },
			{ "<leader>T", group = "[T]est" },
		},
	},
}
